# Generated by Django 4.0.5 on 2022-07-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefas',
            name='imagem',
            field=models.URLField(blank=True, null=True, verbose_name='Imagem'),
        ),
    ]
